/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SkillsRadarRouteImport } from './routes/skills-radar'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as PlayDailyRouteImport } from './routes/play/daily'
import { Route as HistoryIdRouteImport } from './routes/history/$id'
import { Route as CampaignLevelIdRouteImport } from './routes/campaign/$level/$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRadarRoute = SkillsRadarRouteImport.update({
  id: '/skills-radar',
  path: '/skills-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/campaign/',
  path: '/campaign/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDailyRoute = PlayDailyRouteImport.update({
  id: '/play/daily',
  path: '/play/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignLevelIdRoute = CampaignLevelIdRouteImport.update({
  id: '/campaign/$level/$id',
  path: '/campaign/$level/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/skills-radar': typeof SkillsRadarRoute
  '/status': typeof StatusRoute
  '/history/$id': typeof HistoryIdRoute
  '/play/daily': typeof PlayDailyRoute
  '/campaign': typeof CampaignIndexRoute
  '/history': typeof HistoryIndexRoute
  '/campaign/$level/$id': typeof CampaignLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/skills-radar': typeof SkillsRadarRoute
  '/status': typeof StatusRoute
  '/history/$id': typeof HistoryIdRoute
  '/play/daily': typeof PlayDailyRoute
  '/campaign': typeof CampaignIndexRoute
  '/history': typeof HistoryIndexRoute
  '/campaign/$level/$id': typeof CampaignLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/skills-radar': typeof SkillsRadarRoute
  '/status': typeof StatusRoute
  '/history/$id': typeof HistoryIdRoute
  '/play/daily': typeof PlayDailyRoute
  '/campaign/': typeof CampaignIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/campaign/$level/$id': typeof CampaignLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/sign-in'
    | '/sign-up'
    | '/skills-radar'
    | '/status'
    | '/history/$id'
    | '/play/daily'
    | '/campaign'
    | '/history'
    | '/campaign/$level/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/sign-in'
    | '/sign-up'
    | '/skills-radar'
    | '/status'
    | '/history/$id'
    | '/play/daily'
    | '/campaign'
    | '/history'
    | '/campaign/$level/$id'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/sign-in'
    | '/sign-up'
    | '/skills-radar'
    | '/status'
    | '/history/$id'
    | '/play/daily'
    | '/campaign/'
    | '/history/'
    | '/campaign/$level/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SkillsRadarRoute: typeof SkillsRadarRoute
  StatusRoute: typeof StatusRoute
  HistoryIdRoute: typeof HistoryIdRoute
  PlayDailyRoute: typeof PlayDailyRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  CampaignLevelIdRoute: typeof CampaignLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-radar': {
      id: '/skills-radar'
      path: '/skills-radar'
      fullPath: '/skills-radar'
      preLoaderRoute: typeof SkillsRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/daily': {
      id: '/play/daily'
      path: '/play/daily'
      fullPath: '/play/daily'
      preLoaderRoute: typeof PlayDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$level/$id': {
      id: '/campaign/$level/$id'
      path: '/campaign/$level/$id'
      fullPath: '/campaign/$level/$id'
      preLoaderRoute: typeof CampaignLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SkillsRadarRoute: SkillsRadarRoute,
  StatusRoute: StatusRoute,
  HistoryIdRoute: HistoryIdRoute,
  PlayDailyRoute: PlayDailyRoute,
  CampaignIndexRoute: CampaignIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  CampaignLevelIdRoute: CampaignLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
